# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 925ace29d4995cd2397e92d9fdae2c57255e5becc7a01789f3fdccf6dd1f142d47a7ddcc411d7236599eff88a7b439e1c852fa5f402fae695a99e497e59653ac

test:
  secret_key_base: 22fc8afd66c90a68cd567c2cf26e0cbe323077209c03615f726ebce7e4d98c58fd1fef31a1a01267f213a64bef4dbcc6a7b04c96015fb24fbf2c91d89cfc4bf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
